server:
  port: 8080
  
camunda:
  bpm:
    filter:
      create: All tasks
    admin-user:
      id: admin 
      password: 123
    database:
      schema-update: true
      
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myapp 
    username: root 
    password: root